#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Zealot Ke <chzealot@gmail.com>
# Copyright (C) losthit.com 2011

''' colorize gcc
'''

import os
import sys

import colorizer
from colorizer import Colorizer

class ColorGcc(colorizer.Colorizer):
    DEFAULT_PROGNAME = 'gcc'
    DEFAULT_CONFIG_NAME = 'colorgcc.rc'
    def initialize(self):
        print self._progname
        print self._config_name
        print self._config_file
        return

if __name__ == '__main__':
    colorizer.main(globals())
